receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Support for the zipkin exporter will be removed in December 2026 https://opentelemetry.io/docs/specs/otel/trace/sdk_exporters/zipkin/.
  # The new zipkin-otel image supports otel (no gRPC) as the replacement https://github.com/openzipkin-contrib/zipkin-otel.
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  otlp_http:
    endpoint: http://zipkin:9411

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health"

processors:
  filter/drop-healthchecks:
    traces:
      span:
        - 'resource.attributes["service.name"] == "debezium-connect" and attributes["http.route"] == "/"'
        - 'resource.attributes["service.name"] == "debezium-connect" and attributes["http.route"] == "/connectors"'
        - 'resource.attributes["service.name"] == "debezium-connect" and attributes["db.operation"] == "SELECT"'
        - 'resource.attributes["host.name"] == "debezium" and attributes["http.request.method"] == "GET"'

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/drop-healthchecks]
      # Replace 'otlp_http' with 'zipkin' if you want to use the zipkin exporter instead of the otlp_http exporter.
      exporters: [otlp_http]
