receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health"
    # For otel/opentelemetry-collector version 0.133 and newer (maybe).
    # CheckCollectorPipeline:
    #   Enabled: true
    #   Interval: 5s
    #   ExporterFailureThreshold: 1

processors:
  filter/drop-healthchecks:
    traces:
      span:
        - 'resource.attributes["service.name"] == "debezium-connect" and attributes["http.route"] == "/"'
        - 'resource.attributes["service.name"] == "debezium-connect" and attributes["http.route"] == "/connectors"'
        - 'resource.attributes["service.name"] == "debezium-connect" and attributes["db.operation"] == "SELECT"'

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/drop-healthchecks]
      exporters: [zipkin]
