spring:
  application:
    name: outbox-pattern
    solution: example
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        # Optional: Naming strategy for snake_case DB columns (default).
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  output:
    ansi:
      # Supported values are ALWAYS, DETECT (default), and NEVER.
      enabled: always
  jackson:
    default-property-inclusion: non_null
    # Optional: Use UTC timezone for timestamps (default).
    time-zone: UTC
  mvc:
    # Enables NoHandlerFoundException for 404 errors. Set also spring.web.resources.add-mappings to false.
    throw-exception-if-no-handler-found: true
  web:
   resources:
     add-mappings: false
  lifecycle:
    # Works with server.shutdown to define maximum time before forcing shutdown. (Default: 30s)
    timeout-per-shutdown-phase: 30s

server:
  port: 9080
  tomcat:
    baseDir: "./target"
    accesslog:
      enabled: false
      directory: "/logs"
      # MDC values are not supported.
      pattern: "%h %l %u %t \"%r\" %s %b"
      rotatable: true
  # Listens for shutdown signals and lets beans close properly, including connection pools. (Default: immediate)
  shutdown: graceful

management:
  server:
    port: 9081
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState,ping
        readiness:
          include: readinessState,diskSpace
    info:
      enabled: true
      git:
        enabled: true
        mode: full
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      defaults:
        enabled: true
      simple:
        enabled: true
      prometheus:
        enabled: true
    enable:
      all: false
      jvm.memory: true
      logback: true
      process: true
      system: true
      http: true
      jdbc: true
      hikaricp: true
      outboxpattern: true
  otlp:
    tracing:
      endpoint: http://localhost:4317
      transport: grpc
      export:
        enabled: true
  tracing:
    enabled: true
    propagation:
        # Combines produce and consume properties into one.
        # Opted to not support legacy B3 standard.
        type: w3c
    sampling:
      # Sample 100% of traces (good for dev/demo).
      probability: 1.0
    # Baggage in Spring Boot requires explicit whitelisting.
    baggage:
      # Fields available for local use and correlation and tag fields below.
      local-fields: []
      # Fields that will propagate downstream. Available locally as well.
      remote-fields: promo
      correlation:
        # Fields that will be added to the MDC.
        fields: promo,region
      # Fields that will be added to span attributes, which can be used later
      # for filtering in tools like Zipkin.
      # NOTE: Currently there is a bug in the framework that doesn't add these. I've implemented
      # a workaround, so you can ignore the log entry 'Will propagate new baggage context for entries {}'.
      tag-fields: promo,region
  observations:
    enabled: true
    # Global tags that are added to metrics, traces (spans), and logs for filtering.
    key-values:
      foobar: example
      "service.environment": ${spring.profiles.active:local}
    # Resource label for the source of data that is used by OTel-natve backends.
    resource-attributes: {}

logging:
  pattern:
    # Has a trailing space so that it is separated from the thread name that comes right after it by default.
    correlation: "[%X{traceId:-},%X{spanId:-},%X{X-Correlation-Id:-}] "
  file:
    # Normally something like: /usr/share/applog.
    path: ./target/logs
  level:
    # Shows the connection mode used by the OTLP exporter on bootup.
    io.opentelemetry.exporter: DEBUG
    
    # Uncomment the below to see important details about the handling of baggage,
    # and export related connectivity issues like timeouts that happen asynchronously.
    # NOTE: For management.tracing.baggage.tag-fields workaround, setting to INFO instead of DEBUG.
    io.micrometer.tracing: INFO
#    io.opentelemetry: DEBUG
    
    # Uncomment the below to see the SQL statements with parameter bindings.
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.orm.jdbc.bind: TRACE
