kafka:
  authorization:
      superUsers:
      - CN=kafka-ui
      - CN=connect-cluster
  rackTopology:
    enabled: false

nodePools:
  broker:
    annotations:
      strimzi.io/next-node-ids: "[0-9]"
  kraft-controller:
    annotations:
      strimzi.io/next-node-ids: "[10-19]"

crds:
  upgradeJob:
    enabled: true
  deleteJob:
    enabled: true

strimzi-drain-cleaner:
  enabled: false
  certManager:
    create: false
