####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a micro base image, tuned for Quarkus native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
#
# Before building a container image from the Dockerfiles shown below, you need to update the default .dockerignore file,
# as it filters everything except the target directory. In order to build inside a container, you need to copy the src
# directory. Thus, edit your .dockerignore and remove the * line.
#
# Build the container image with:
#
# docker build -f src/main/docker/Dockerfile.native-micro-multistage -t stevenjdh/outbox-pattern .
# NOTE: Execute 'mvnw git-commit-id:revision' to pre-generate git.properties before running command above.
#
# Then run the container using:
#
# docker run -i --rm \
#     -e QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://host.docker.internal:5432/orders_db  \
#     -e QUARKUS_DATASOURCE_USERNAME=postgres \
#     -e QUARKUS_DATASOURCE_PASSWORD=password \
#     -p 9080:9080 -p 9081:9081 \
#     stevenjdh/outbox-pattern
#
###

## Stage 1 : build with maven builder image with native capabilities.
FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-21 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.8.1:go-offline
COPY src /code/src
COPY target/classes/git.properties /code/target/classes/git.properties
RUN ./mvnw -B package -Dnative -DskipTests -DskipITs=false -DskipGitCommitId=true

## Stage 2 : create the docker final image.
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --chmod=0755 --from=build /code/target/*-runner /work/application

EXPOSE 9080 9081
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]