auth:
  username: postgres
  password: password
  database: orders_db

primary:
  extendedConfiguration: |
    wal_level = logical
    max_wal_senders = 10
    max_replication_slots = 10
    wal_sender_timeout = 0
  initdb:
    scripts: {}

# Temporary workaround until a more recent update is tested.
global:
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/postgresql
