apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-connect-plugins-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # TODO: Change this path to your local path where the connector plugins are stored if needed.
    path: /mnt/c/Users/Public/Downloads/kafka-connect-plugins
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: "" # Leave empty to avoid binding to default storage class.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-connect-plugins-pvc
  namespace: strimzi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: ""  # Leave blank to match the PV, which has no class.
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  # No ACLs defined, so add user as super user in Kafka resource.
  name: kafka-ui
  labels:
    strimzi.io/cluster: my-strimzi-cluster
  namespace: strimzi
spec:
  authentication:
    type: tls
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  # No ACLs defined, so add user as super user in Kafka resource.
  name: connect-cluster
  labels:
    strimzi.io/cluster: my-strimzi-cluster
  namespace: strimzi
spec:
  authentication:
    type: tls
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-offsets
  labels:
    strimzi.io/cluster: my-strimzi-cluster
  namespace: strimzi
spec:
  partitions: 25
  replicas: 3
  config:
    retention.ms: "604800000"
    cleanup.policy: compact 
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-configs
  labels:
    strimzi.io/cluster: my-strimzi-cluster
  namespace: strimzi
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: "604800000"
    cleanup.policy: compact 
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-status
  labels:
    strimzi.io/cluster: my-strimzi-cluster
  namespace: strimzi
spec:
  partitions: 5
  replicas: 3
  config:
    retention.ms: "604800000"
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  # Topic names in Kubernetes are required to be in lowercase, and are case sensitive. The below
  # error will appear in the Connect logs if auto create topics is disabled and there is a mismatch.
  # Error: The metadata response from the cluster reported a recoverable issue with correlation id 1+n : {outbox.Order=UNKNOWN_TOPIC_OR_PARTITION}.
  name: outbox.order
  labels:
    strimzi.io/cluster: my-strimzi-cluster
  namespace: strimzi
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: "604800000"
    cleanup.policy: compact 
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: outbox.unknown
  labels:
    strimzi.io/cluster: my-strimzi-cluster
  namespace: strimzi
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: "604800000"
    cleanup.policy: compact 
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: outbox.failed.events-dlt
  labels:
    strimzi.io/cluster: my-strimzi-cluster
  namespace: strimzi
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: "604800000"
    cleanup.policy: compact 
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    # use-connector-resources configures this KafkaConnect
    # to use KafkaConnector resources to avoid
    # needing to call the Connect REST API directly.
    strimzi.io/use-connector-resources: "true"
  namespace: strimzi
spec:
  replicas: 1
  bootstrapServers: my-strimzi-cluster-kafka-bootstrap.strimzi.svc.cluster.local:9094
  tls:
    trustedCertificates:
      - secretName: my-strimzi-cluster-cluster-ca-cert
        pattern: "*.crt"
  authentication:
    type: tls
    certificateAndKey:
      secretName: connect-cluster
      certificate: user.crt
      key: user.key
  # Config reference: https://kafka.apache.org/documentation/#connectconfigs
  # Properties with the following prefixes cannot be set: ssl., sasl., security.,
  # listeners, plugin.path, rest., bootstrap.servers, consumer.interceptor.classes,
  # producer.interceptor.classes (with the exception of: ssl.endpoint.identification.algorithm,
  # ssl.cipher.suites, ssl.protocol, ssl.enabled.protocols).
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker.
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  template:
    pod:
      volumes:
        - name: kafka-connect-plugins
          persistentVolumeClaim:
            claimName: kafka-connect-plugins-pvc
    connectContainer:
      volumeMounts:
        - name: kafka-connect-plugins
          mountPath: /mnt/opt/kafka/plugins
      env:
        - name: KAFKA_CONNECT_PLUGIN_PATH
          # We are only allowed to mount under /mnt/, so kept the path similar to the default, /opt/kafka/plugins.
          value: /mnt/opt/kafka/plugins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: debezium-connect-secret-access
  namespace: strimzi
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debezium-connect-secret-access-binding
  namespace: strimzi
subjects:
- kind: ServiceAccount
  name: debezium-connect-cluster-connect
  namespace: strimzi
roleRef:
  kind: Role
  name: debezium-connect-secret-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kafkaui-to-kafkaconnect
  namespace: strimzi
spec:
  podSelector:
    matchLabels:
      strimzi.io/cluster: debezium-connect-cluster
      strimzi.io/kind: KafkaConnect
      strimzi.io/name: debezium-connect-cluster-connect
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: kafka-ui
      ports:
        - protocol: TCP
          port: 8083
  policyTypes:
    - Ingress
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: outbox-connector
  labels:
    strimzi.io/cluster: debezium-connect-cluster
  namespace: strimzi
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  # When setting tasksMax to 1, make sure to configure errors.* to send failed events
  # to a dead letter topic or all other events will be blocked indefinitely.
  tasksMax: 1
  autoRestart:
    enabled: true
    maxRestarts: 10
  # Config reference: https://kafka.apache.org/documentation/#sourceconnectconfigs
  config:
    database.hostname: my-postgresql-hl.strimzi.svc.cluster.local
    database.port: "5432"
    database.user: postgres
    database.password: ${secrets:strimzi/my-postgresql:postgres-password}
    database.dbname: orders_db
    database.server.name: example
    publication.name: debezium_pub
    plugin.name: pgoutput
    slot.name: debezium_slot

    topic.prefix: debezium
    table.include.list: public.outbox_event

    transforms: outbox,topicRouter

    transforms.outbox.type: io.debezium.transforms.outbox.EventRouter
    transforms.outbox.table.field.event.id: id
    transforms.outbox.table.field.event.type: type
    transforms.outbox.table.field.event.aggregate.type: aggregate_type
    transforms.outbox.table.field.event.key: aggregate_id
    transforms.outbox.table.field.event.payload: payload
    transforms.outbox.tracing.span.context.field: tracing_span_context
    transforms.outbox.table.field.event.timestamp: timestamp
    # We keep a copy of the 'aggregate_type' in the header in case of unknown topic routing, and 'type' for filtering in consumers.
    transforms.outbox.table.fields.additional.placement: "type:header,aggregate_type:header,tracing_span_context:header:baggage"
    transforms.outbox.table.expand.json.payload: "true"

    transforms.outbox.route.by.field: aggregate_type
    # If auto.create.topics.enable=false in Kafka, instead of setting (.*), whitelist known
    # aggregate types like ^(order|campaign)$ and send everything else to a catch all topic.
    # Otherwise, any topic not pre-created will cause the connector to retry indefinitely.
    transforms.outbox.route.topic.regex: ^(order)$
    transforms.outbox.route.topic.replacement: outbox.$1
    
    # This is for routing unknown aggregate types to a catch all topic instead of failing indefinitely.
    transforms.topicRouter.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.topicRouter.regex: "^(?!outbox\\.(order)).*$"
    transforms.topicRouter.replacement: outbox.unknown

    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "false"
    replication.factor: -1

    errors.tolerance: none
    errors.retry.timeout: 60000
    # This is for actual processing errors. Errors like the producer cannot find the target topic
    # because auto.create.topics.enable=false, or when RecordTooLargeException or
    # UnknownTopicOrPartitionException are thrown will all cause the task to retry indefinitely
    # because Kafka Connect considers the failure transient.
    errors.deadletterqueue.topic.name: outbox.failed.events-dlt
    errors.deadletterqueue.topic.replication.factor: -1
    errors.deadletterqueue.context.headers: true
    errors.log.enable: false
    errors.log.include.messages: false
